### PR TITLE
Propagate headers to WS upstream using connection_init

### PR DESCRIPTION
**Pull request by v0id3r**
Solves #290 

We already have `http.Header` and include it when hashing.
However, we do not propagate the actual value during the init+ack handshake.

With this change, it will send headers as payload.
Works perfectly together with client-facing WS init hook from #275 and makes it possible to propagate init payload from user WS to federation WS. Entities requests also follow and headers are attached to outgoing requests to data sources.

`playground` sends headers as payload instead of regular headers for subscriptions.
`gqlgen` has a special hook on WebSocket for init.

Going to add specific tests, but it is at least backward-compatible with existing suite.

### CODE REVIEW

**Comment by v0id3r** [comment]
@chedom Hi, you mentioned that you've also implemented headers propagation at your fork. May I ask you to provide some feedback here, if any?

**Comment by chedom** [comment]
Hi @v0id3r , my [solution](https://github.com/chedom/graphql-go-tools/commit/afb1f7a98bd206f9292a73daf8b476fbff99e4ec#diff-264442409bb80cf3c5d65dfc33eb05352fa6e349e56d7ca111a9e8dc476f4736) is very close to your implementation.

**Comment by bailycase** [comment]
Is there any update on this being merged?

**Comment by spetrunin** [comment]
closed in favor of https://github.com/wundergraph/graphql-go-tools/pull/425

**Pull request closed without merging**
