### PR TITLE
fix: update websocket handlers to eliminate goroutine leaks (#796)

### PR DESCRIPTION
**Pull request by BenjaminYong**
Hi team,

Please see the suggested fixes to address the issue I raised: https://github.com/wundergraph/graphql-go-tools/issues/796

After this change, the websocket handlers and their goroutines are closing as expected. As a result, my memory usage is much more lower and no longer leaking.
image

Thanks,
Benny

### CODE REVIEW

**Review by jensneuse — APPROVED** [review]

**Comment by jensneuse** [comment]
Please fix CI. ;-)

**Comment by BenjaminYong** [comment]
Sorry guys, been struggling to reproduce, though I'm on darwin/arm64. Mine doesn't fail like the CI does, any tips?
image

**Comment by Aenimus** [comment]
@jensneuse @devsergiy @StarpTech CI is passing.

**Comment by devsergiy** [comment]
@BenjaminYong added in tag [v1.67.3](https://github.com/wundergraph/graphql-go-tools/releases/tag/v1.67.3)

**Pull request merged**
