### PR TITLE
Ability to send custom headers to subservices

### PR DESCRIPTION
**Pull request by daniil-kzn**

### CODE REVIEW

**Comment by jensneuse** [comment]
Can you add any sort of test to make it clear what this PR changes/fixes?

**Comment by daniil-kzn** [comment]
Added simple test to check that request from context will pass to the final request to subservice.

**Comment by jensneuse** [comment]
I see what you're trying to do.
Do you think the following existing solution already solves your problem?
https://github.com/wundergraph/graphql-go-tools/blob/607a7ec39dbf195cfe1ccf8b8c1f837f4670bbb0/pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go#L180

Or is an additional solution required?

**Comment by daniil-kzn** [comment]
@jensneuse I am not sure the solution helps me because I have no idea how to inject plan.Configuration to g.engine in here
[plan.Configuration](https://github.com/wundergraph/graphql-go-tools/blob/master/examples/federation/gateway/http/http.go#L30)

**Comment by daniil-kzn** [comment]
@jensneuse Any hints how can I configurate Headers from the method ?
https://github.com/wundergraph/graphql-go-tools/blob/607a7ec39dbf195cfe1ccf8b8c1f837f4670bbb0/examples/federation/gateway/http/http.go#L18

**Comment by spetrunin** [comment]
@daniil-kzn you don't have to inject plan configuration on the execution stage

You have a place where you defining your datasource configuration and passing it to execution engine constructor
So you could add similar configuration as in example propose by @jensneuse 

After that you could send you headers along with request and they will be forwarded to upstream

**Comment by daniil-kzn** [comment]
@spetrunin I have the same code as in the gateway example https://github.com/wundergraph/graphql-go-tools/tree/master/examples/federation/gateway and there is the datasource configuration only in the datasouirce_poller
I tried to add Authorization header here: 
https://github.com/wundergraph/graphql-go-tools/blob/d2fb53dada07e7defacb7b36b7c223d6b3750f2d/examples/federation/gateway/datasource_poller.go#L156

but it didn't help to send the header within an regulal request to upstream.

**Comment by daniil-kzn** [comment]
@jensneuse @spetrunin So, guys, let's merge it or fix the issue https://github.com/wundergraph/graphql-go-tools/issues/459

**Pull request closed without merging**
