### PR TITLE
fix for handling non existing field of input type in astnormalization

### PR DESCRIPTION
**Pull request by phob0s-pl**
This fix is for normalization of request where one of nested subfields of input type does not exist.

This can be checked by running such a query in input_coercion_for_list_test.go

```
query {
  inputWithListNestedList(input: {
    nested: {non_existing_field: true},
  }) {
    id
    name
  }
}
```

fixes https://github.com/wundergraph/graphql-go-tools/pull/559

### CODE REVIEW

**Comment by jensneuse** [comment]
Thanks for the contribution.
Will this issue not be caught by validating the Operation?

**Comment by phob0s-pl** [comment]
@jensneuse  , no because flow of engine is following normalization->then validate against schema. 

```go
func (e *ExecutionEngineV2) Execute(ctx context.Context, operation *Request, writer resolve.FlushWriter, options ...ExecutionOptionsV2) error {
	if !operation.IsNormalized() {
		result, err := operation.Normalize(e.config.schema)
		if err != nil {
			return err
		}

		if !result.Successful {
			return result.Errors
		}
	}

	result, err := operation.ValidateForSchema(e.config.schema)
```

**Comment by jensneuse** [comment]
I see, makes sense.
Can you add a test to cover this code change?

**Comment by phob0s-pl** [comment]
@jensneuse Hi, I have added the test for that fix

**Review by devsergiy — APPROVED** [review]

**Pull request merged**
