### PR TITLE
fix: ignore __typename when setting select reason

### LINKED ISSUE #830: Could not plan the operation missing path
I have a federated graph using a version of the federation example as my gateway.

Most of my backends extend the Company-type and add fields to it.

Some queries now fails with the below error but not all and I see no pattern to which fail and which succeed. In some cases it's even different for queries which target the same backend that behaves differently.

`internal: bad datasource configuration - could not plan the operation. missing path: [query.company.__typename]`

What might be the problem? What can I do to provide more information to identify the problem?

### PR DESCRIPTION
**Pull request by argoyle**
Fixes #830

### CODE REVIEW

**Comment by argoyle** [comment]
Of course. Just wanted to get some hint on if this was reasonable or if it will break something else.

**Comment by devsergiy** [comment]
Hi @argoyle 

Thanks a lot for your contribution
I don't know currently which side effects it could have

Currently, we are doing a rewrite of this functionality, which may fix your issue

I will let you know when we have some results

**Comment by argoyle** [comment]
@devsergiy Should I hold off on creating a test for this then?

**Comment by argoyle** [comment]
Added a couple of tests anyway

**Pull request closed without merging**
