### PR TITLE
Feature/ws init func

### PR DESCRIPTION
**Pull request by chedom**
Add possibility to check initial payload to see whether to accept the websocket connection.
Example: authenticate user from websocket connection and save session of user in context.

### CODE REVIEW

**Comment by spetrunin** [comment]
Hi @chedom 
could you have a look at this commit https://github.com/jensneuse/graphql-go-tools/commit/7375417588e2936e48015650a6c9f673ec0ef413

Does it solve a problem for you?

**Comment by chedom** [comment]
> Hi @chedom
> could you have a look at this commit [7375417](https://github.com/jensneuse/graphql-go-tools/commit/7375417588e2936e48015650a6c9f673ec0ef413)
> 
> Does it solve a problem for you?

Hi @spetrunin.
No, it doesn't solve the problem for me.
I added means to authenticate WebSocket  connection(it must be done once)  but your hook is called every time when client sends new operation (starts new subscription or query/mutation through websocket).
Example:
```
|------------|--------------|---------|-----> t
A            B              C         D
``` 
Where:
`A` - client initiates websocket connection (sends ConnectionInit message)
`B` - client sends Subscription1 (sends ConnectionStart message)
`C` - client sends Subscription2 (sends ConnectionStart message)
`D` - client sends mutation through websocket (client preferred to use WS as maint transport layer for all operations) (sends ConnectionStart message)

`WebsocketInit` func will be called only  at point `A` (gets token from initial payload, resolves user session and stores it in connection context, example from [gqlgen](https://gqlgen.com/recipes/authentication/#websockets)).
`WebsocketBeforeStartHook` will be called at points `B`, `C`, `D`.

I have checked how you use `WebsocketBeforeStartHook` in [tyk](https://github.com/TykTechnologies/tyk).  
I would propose you to migrate from the hook to operation middleware #284. It allows you to move logic from [websocket hook](https://github.com/TykTechnologies/tyk/blob/master/gateway/mw_graphql.go#L286) and http middlewares([this](https://github.com/TykTechnologies/tyk/blob/master/gateway/mw_graphql_complexity.go#L33) and [this](https://github.com/TykTechnologies/tyk/blob/master/gateway/mw_graphql_granular_access.go#L35)) to single operation middleware.

**Comment by chedom** [comment]
@jensneuse, @spetrunin what do you think of  PR ?

**Comment by argoyle** [comment]
I have the same problem. What's needed to get this PR going again and hopefully merged?

**Comment by jensneuse** [comment]
> I have the same problem. What's needed to get this PR going again and hopefully merged?

Fork the PR branch. Merge master. I'll have a look to merge.

**Comment by spetrunin** [comment]
closed with https://github.com/wundergraph/graphql-go-tools/pull/406

**Pull request closed without merging**
